const Courses=[
    {
        id:'1',
        title:'Web Development',
        image:require('../../assets/image1.jpg'),
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum sequi consectetur, id et odit architecto",
        course1:'Web',
        course2:'Native',
        course3:'js',
        price:6000,
    },
    {
        id:'2',
        title:'Development',
        image:require('../../assets/image2.jpg'),
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum sequi consectetur, id et odit architecto",
        course1:'Web',
        course2:'Native',
        course3:'js',
        price:6000,
    },
    {
        id:'3',
        title:'Full Stack',
        image:require('../../assets/image3.jpg'),
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum sequi consectetur, id et odit architecto",
        course1:'Web',
        course2:'Native',
        course3:'js',
        price:6000,
    },
    {
        id:'4',
        title:'Native Development',
        image:require('../../assets/image4.jpg'),
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum sequi consectetur, id et odit architecto",
        course1:'Web',
        course2:'Native',
        course3:'js',
        price:6000,
    },
    {
        id:'5',
        title:'JavaScript Development',
        image:require('../../assets/image5.jpg'),
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum sequi consectetur, id et odit architecto",
        course1:'Web',
        course2:'Native',
        course3:'js',
        price:6000,
    },
    {
        id:'6',
        title:'Mern',
        image:require('../../assets/image6.jpg'),
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum sequi consectetur, id et odit architecto",
        course1:'Web',
        course2:'Native',
        course3:'js',
        price:6000,
    },
]

export default Courses;